language: python
cache: pip

python:
 - pypy3
 - 3.5
 - 3.6
 - 3.7
 - 3.8
 - 3.9-dev
 - 3.10-dev

matrix:
  fast_finish: true

install:
  - pip install -U pip
  - pip install -U tox-travis

script:
  - tox

after_success:
  - pip install -U codecov && codecov --flags TravisCI
