version: 2
 jobs:
   python2_test:
     docker:
       - image: circleci/python:2.7
     steps:
       - checkout
       - run:
           name: Tests
           command: |
            python setup.py test
            pylint **/**.py --rcfile=.pylintrc
   python3_test:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - run:
           name: Tests
           command: |
             python setup.py test
             pylint **/**.py --rcfile=.pylintrc


